### ISSUE TITLE
Watchdog and adc traits are missing from prelude

### ISSUE THREAD

**Issue by david-sawatzke** [rust-embedded/embedded-hal#117]
@HarkonenBade and I have run into the issue, that both the watchdog and the adc traits are missing from `src/prelude.rs` while implementing them in https://github.com/stm32-rs/stm32f0xx-hal/pull/13 and https://github.com/stm32-rs/stm32f0xx-hal/pull/12.

**Comment by therealprof** [comment]
I'd be happy to approve a PR. ;)
