### ISSUE TITLE
I2c WriteIter use Item = &u8

### ISSUE THREAD

**Issue by MabezDev** [rust-embedded/embedded-hal#154]
I've been playing with an I2c EEPROM chip recently in which writes are performed in one I2c transaction, i.e:

```
START -> 16bit address -> data -> STOP
```

I figured I would use write iter to chain the address bytes and data together, like so:

```rust
pub fn write(&mut self, address: u16, buffer: &[u8]) -> Result<(), <I as WriteIter>::Error> {
    let addr_bytes = [
        ((address & 0xFF00) >> 8) as u8,
        (address & 0x00FF) as u8,
    ];
    self.i2c.write(self.dev_addr, addr_bytes.iter().chain(buffer.iter()))
}
```

Which is really clean - unfortunately because `Item = u8` to do this we have to consume the buffer. I think changin the `WriteIter` signature to
```rust
/// Blocking write (iterator version)
#[cfg(feature = "unproven")]
pub trait WriteIter {
    /// Error type
    type Error;

    /// Sends bytes to slave with address `addr`
    ///
    /// # I2C Events (contract)
    ///
    /// Same as `Write`
    fn write<'a, B>(&mut self, addr: u8, bytes: B) -> Result<(), Self::Error>
    where
        B: IntoIterator<Item = &'a u8>;
}
```
makes more sense, and also makes the iterator version more similar to the simple write version.

**Comment by eldruin** [comment]
Great idea! I think then I could get rid of all the copying for page writes in the [eeprom24x](https://crates.io/crates/eeprom24x) driver.
