### ISSUE TITLE
Video call scheduling

### ISSUE THREAD

**Issue by thejpster** [rust-embedded/embedded-hal#187]
At the WG meeting it was agreed the HAL team would meet to thrash out a way forward for the HAL. This would include:

The agenda of that meeting to cover:

* How we organize embedded-hal (one crate vs many)
* How we "mainline" items
* What we do about the state of things (v2, v3) right now

I propose Thursday 27 Feb at 1900 Europe/London. VC details to follow.

@rust-embedded/hal please confirm whether you can or cannot make this time. Please also suggest further agenda items if required.

**Comment by therealprof** [comment]
Works for me.

**Comment by Disasm** [comment]
Works for me too

**Comment by ryankurte** [comment]
oops, guess i missed this one. did it happen / did anyone take minutes?

**Comment by therealprof** [comment]
@ryankurte That meeting did not happen, due to being too short on notice to arrange.
@jamesmunns Do you have any preferred date? I'll be travelling next week so that won't really work for me.

**Comment by thejpster** [comment]
Oops. I proposed a time and totally forgot to follow up and set up a call. My bad.

Next week I've only got Tuesday evening free.

**Comment by therealprof** [comment]
Next week I'm at a conference.

**Comment by ryankurte** [comment]
How about on the 11th, directly after the WG meeting?

**Comment by thejpster** [comment]
I can do 2020-03-11T20:00:00Z.

**Comment by Disasm** [comment]
I believe, meeting will be on 10th, but this date works for me too

**Comment by ryankurte** [comment]
> I believe, meeting will be on 10th, but this date works for me too

ahh yes, sorry, i intended that to be on the 10th @ 20:00 GMT but forgot to convert the date (i live in the GMT+13 future so this is a morning meeting for me 🙃)


:tada: for 2020-03-10T20:00Z
:rocket: for 2020-03-11T20:00Z

**Comment by ryankurte** [comment]
So confirming availability on 2020-03-10T20:00Z (directly following the embedded WG meeting / ~22 hours from now)

- [x] @ryankurte 
- [x] @therealprof 
- [ ] @thejpster 
- [ ] @Disasm 

Once y'all have confirmed I'll ask someone (probably @jamesmunns) nicely to add a calendar event with a hangouts chat

**Comment by thejpster** [comment]
> So confirming availability on 2020-03-10T20:00Z (directly following 
the embedded WG meeting / ~22 hours from now)

Works for me.

**Comment by jamesmunns** [comment]
I can attend/set up a meeting. It'll be on Zoom.

**Comment by jamesmunns** [comment]
The meeting details are:


https://zoom.us/j/894390824

Password 070334

**Comment by ryankurte** [comment]
thanks team!

meeting notes: https://hackmd.io/ck-xRXtMTmKYXdK5bEh82A?view#Final-Summary
