### ISSUE TITLE
blocking::spi::write_iter has a needless Default blocker?

### ISSUE THREAD

**Issue by almindor** [rust-embedded/embedded-hal#208]
Why does `blocking::spi` have this [custom `Default`](https://github.com/rust-embedded/embedded-hal/blob/master/src/blocking/spi.rs#L83) trait?

It's making using things like `IntoIterator<Item = u8>` impossible with `write_iter` with errors like:

```rust
embedded_hal::blocking::spi::write_iter::Default<u8>` is not implemented for `nrf52832_hal::Spim<nrf52832_hal::nrf52832_pac::SPIM0>
```

I don't see why this default is even needed.

**Comment by therealprof** [comment]
I'm struggling a bit to come up with an efficient &[u16] to &[u8] conversion that doesn't suck to test the versatility (and performance) of that approach.

**Comment by almindor** [comment]
Even without conversion tho, say we want to use [Into]Iterators for greater flexibility, this Default trait is a blocker.

If there's no reason for it to exist I'd make a PR to remove + unify I2C and SPI naming (`write` vs `write_iter` currently).

**Comment by almindor** [comment]
Nvm, figured it out with Disasm's help.
