### ISSUE TITLE
error: trait objects without an explicit `dyn` are deprecated

### ISSUE THREAD

**Issue by reneherrero** [rust-embedded/embedded-hal#213]
Hi,

I'm getting the following error when trying to compile the library with rust 1.43.1:
```
error: trait objects without an explicit `dyn` are deprecated
   --> src/fmt.rs:6:29
    |
6   | impl<Word, Error> Write for ::serial::Write<Word, Error=Error>
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn (::serial::Write<Word, Error=Error>)`
    |
```

Only way I can see to make it compile is by removing `#![deny(warnings)]` from `lib.rs`, but that doesn't seem right?

I'm also not getting why I can reference the embedded-hal crate from another project (`embedded-hal = "0.2.3"`) without issues, but if I reference the code (`embedded-hal = { path="../../embedded-hal/" }`) I get the above mentioned error?

Thanks in advance,

**Comment by ryankurte** [comment]
Thanks for the report! This should be resolved in `0.2.4` and in the current (unreleased) branch.
