### ISSUE TITLE
[1.0 alpha] StatefulOutputPin is not exposed in prelude

### ISSUE THREAD

**Issue by Disasm** [rust-embedded/embedded-hal#225]
https://github.com/rust-embedded/embedded-hal/blob/60c9263a83395333f78c0981fadde6876b60c8e9/src/prelude.rs#L18-L22

**Comment by Disasm** [comment]
It's a good idea to check that all the other previously "unproven" traits are exposed too.

**Comment by eldruin** [comment]
This should be solved in #227. Good catch!
