### ISSUE TITLE
tag v0.2.4

### ISSUE THREAD

**Issue by jordens** [rust-embedded/embedded-hal#243]
That tag seems to be missing.
The [link](https://github.com/rust-embedded/embedded-hal/compare/v0.2.3...v0.2.4) to the release diff in the [CHANGELOG](https://github.com/rust-embedded/embedded-hal/blob/v0.2.x/CHANGELOG.md#v024---2020-06-17) does not work.

**Comment by eldruin** [comment]
I added the tag now.
Thanks for letting us know!
