### ISSUE TITLE
ADC trait take self

### ISSUE THREAD

**Issue by David-OConnor** [rust-embedded/embedded-hal#267]
Hi. For the `adc::Channel` trait, do you think we could use ` fn channel(&self)`, so you wouldn't need a separate data structure for each channel? Without this, there's no way to differentiate the channels. It looks like both the STM32 HALs, and `adx1x1x` make a number of structs, where an enum or single struct could be cleaner. Exposing `&self` would let you do this.

From the `ads1x1x` crate:
```rust
pub mod channel {
    /// Measure single-ended signal on input channel 0
    pub struct SingleA0;
    /// Measure single-ended signal on input channel 1
    pub struct SingleA1;
    /// Measure single-ended signal on input channel 2
    pub struct SingleA2;
    /// Measure single-ended signal on input channel 3
    pub struct SingleA3;
    /// Measure signal on input channel 0 differentially to signal on input channel 1
    pub struct DifferentialA0A1;
    /// Measure signal on input channel 0 differentially to signal on input channel 3
    pub struct DifferentialA0A3;
    /// Measure signal on input channel 1 differentially to signal on input channel 3
    pub struct DifferentialA1A3;
    /// Measure signal on input channel 3 differentially to signal on input channel 3
    pub struct DifferentialA2A3;
}
```

Feels like an enum in disguise!

**Comment by Rahix** [comment]
I think this is already case in the pre-release 1.0 versions.  On `master` right now:

https://github.com/rust-embedded/embedded-hal/blob/42218945bfe21fb1611421e77d1b3e76be530ef8/src/adc.rs#L41-L52

**Comment by David-OConnor** [comment]
Oh you're right - already on the repo!
