### ISSUE TITLE
Implement From<PinState> for bool

### ISSUE THREAD

**Issue by sourcebox** [rust-embedded/embedded-hal#427]
`From<bool>` is already implemented for PinState in `digital.rs`, which makes sense for output pins. For input pins, it would make sense to implement the `Into<bool>` trait as well, so a function could take an argument that is either a `PinState` or a `bool`:

```rust
impl Into<bool> for PinState {
    fn into(self) -> bool {
        match self {
            PinState::Low => false,
            PinState::High => true,
        }
    }
}

fn print_state<T: Into<bool>>(state: T) {
    println!("{:?}", state.into());
}

fn main() {
    print_state(false);
    print_state(true);
    print_state(PinState::Low);
    print_state(PinState::High);
}
```

**Comment by Dirbaio** [comment]
It should be `impl From<PinState> for bool`, as you should never impl `Into` manually since it's derived from `From`. Otherwise SGTM! PR welcome :)

**Comment by sourcebox** [comment]
> It should be `impl From<PinState> for bool`, as you should never impl `Into` manually since it's derived from `From`. Otherwise SGTM! PR welcome :)

Yes, you're right. So take this:

```rust
impl From<PinState> for bool {
    fn from(value: PinState) -> bool {
        match value {
            PinState::Low => false,
            PinState::High => true,
        }
    }
}
```
