### ISSUE TITLE
Broken documentation for GPIO23

### ISSUE THREAD

**Issue by VorpalBlade** [rust-embedded/embedded-hal#454]
According to rust-analyzer I'm getting a Gpio23 object (which makes sense, I'm trying to hook up a LED to that GPIO for a test). When I try to find documentation for it however at https://esp-rs.github.io/esp-idf-hal/esp_idf_hal/gpio/index.html it only goes up to Gpio21!?

I presume this is due to this docs being built for a different module, but on docs.rs there is a dropdown to switch between build targets. It would be really useful to have that here.

For context: I'm using and targeting a traditional Xtensa ESP32 module (ESP32-WROVER-IE specifically on a ESP32-DevKitC, this was the only dev board with I2S support and traditional non-LE Bluetooth I could find in stock here in Sweden).

EDIT: Running `cargo doc` to locally build the docs doesn't work either. the esp-idf crates are completely missing from the docs in this case!

**Comment by Dirbaio** [comment]
You should file this issue at https://github.com/esp-rs/esp-idf-hal/

**Comment by VorpalBlade** [comment]
Sorry, too many tabs open while trying to figure out the mess that is embedded rust.
