### ISSUE TITLE
[Feature] Logging and debugging

### ISSUE THREAD

**Issue by elpiel** [rust-embedded/embedded-hal#460]
It would be nice if some of the main structs like spi::Polarity have Debug implemented or defmt::Format somehow, e.g. with a feature.

One thing I'm caution with though is not to rely on any single logging crate.

Other formats like bincode could also benefit from such a no_std improvement

**Comment by MabezDev** [comment]
There are `defmt::Format` derives on most structs behind the `defmt-03` feature now, so I think this can be closed.
