### ISSUE TITLE
SPI `ExclusiveDevice`: access the bus object

### ISSUE THREAD

**Issue by bugadani** [rust-embedded/embedded-hal#467]
Sometimes it might be necessary/useful to access the SPI bus object that is held by an `ExclusiveDevice`. One such case might be adjusting SCLK speed based on some data read from the SPI device.

**Comment by Dirbaio** [comment]
This was discussed a bit in today's meeting. Sounds like a good feature to have. Could you send a PR?

**Comment by bugadani** [comment]
Definitely, if something like an `inner()`/`inner_mut()` pair sound good. I'm on a vacation, though, so earliest is next week.

**Comment by Dirbaio** [comment]
I htink the convention is `inner(), inner_mut()`. We might want to do `into_inner()` too, to deconstruct it.
