### ISSUE TITLE
Doc: display issue

### ISSUE THREAD

**Issue by HaoboGu** [rust-embedded/embedded-hal#543]
In the doc of the latest version [`1.0.0-rc.2`](https://docs.rs/embedded-hal/1.0.0-rc.2/embedded_hal/), the indent of the first line is not correct:

![1561153a638a4319265d8cbe2c156af8](https://github.com/rust-embedded/embedded-hal/assets/8640918/37629a2c-1deb-4b67-b78c-72dae755b4a1)

The current version [`0.2.7`](https://docs.rs/embedded-hal/0.2.7/embedded_hal/) looks good:
![image](https://github.com/rust-embedded/embedded-hal/assets/8640918/8ea8e8dc-a0b0-46f1-bc95-c6941790f903)

It seems that crates.io doesn't support markdown grammar `>`.

**Comment by Dirbaio** [comment]
I think this is a minor cosmetic issue. If you want to improve crates.io CSS, I'm sure they'd accept a PR.
