### ISSUE TITLE
Should `timer::CountDown` be a supertrait for `timer::Periodic`?

### ISSUE THREAD

**Issue by hannobraun** [rust-embedded/embedded-hal#87]
#67 adds a new timer trait that has `timer::CountDown` as a supertrait. Should the same be done for `timer::Periodic`?

I think yes.

cc @therealprof @jonas-schievink

**Comment by Dirbaio** [comment]
I'm going to close this, now that the old timer traits are removed #324.

Discussion for design for the new traits can go in #359 . Linking it so this issue appears there.
